# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Bandcamp'), (2, 'Youtube'), (3, 'Soundcloud')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
