# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161115_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='artist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
