# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161118_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='referrer',
            field=models.URLField(null=True),
        ),
    ]
