# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161121_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
