# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161121_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='played',
        ),
        migrations.AlterField(
            model_name='item',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
