# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161207_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
