# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-13 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20161224_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='played_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
