# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-13 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
